/// Claude Code プラグインに同梱するスキルファイルの埋め込みデータ。
/// 各エントリは (プラグイン skills/ ディレクトリからの相対パス, ファイル内容) のペア。
pub const SKILL_FILES: &[(&str, &str)] = &[
    // --- domain-model-diagram ---
    (
        "domain-model-diagram/SKILL.md",
        include_str!("../skills/domain-model-diagram/SKILL.md"),
    ),
    (
        "domain-model-diagram/templates/entry-point.jsx",
        include_str!("../skills/domain-model-diagram/templates/entry-point.jsx"),
    ),
    (
        "domain-model-diagram/templates/components--EntityBox.jsx",
        include_str!("../skills/domain-model-diagram/templates/components--EntityBox.jsx"),
    ),
    (
        "domain-model-diagram/templates/components--RelationshipLine.jsx",
        include_str!(
            "../skills/domain-model-diagram/templates/components--RelationshipLine.jsx"
        ),
    ),
    (
        "domain-model-diagram/templates/data--entities.example.jsx",
        include_str!("../skills/domain-model-diagram/templates/data--entities.example.jsx"),
    ),
    (
        "domain-model-diagram/templates/data--relationships.example.jsx",
        include_str!(
            "../skills/domain-model-diagram/templates/data--relationships.example.jsx"
        ),
    ),
    // --- wireframe ---
    (
        "wireframe/SKILL.md",
        include_str!("../skills/wireframe/SKILL.md"),
    ),
    (
        "wireframe/templates/entry-point.jsx",
        include_str!("../skills/wireframe/templates/entry-point.jsx"),
    ),
    (
        "wireframe/templates/components--W.jsx",
        include_str!("../skills/wireframe/templates/components--W.jsx"),
    ),
    (
        "wireframe/templates/components--layout.jsx",
        include_str!("../skills/wireframe/templates/components--layout.jsx"),
    ),
    (
        "wireframe/templates/components--primitives.jsx",
        include_str!("../skills/wireframe/templates/components--primitives.jsx"),
    ),
    (
        "wireframe/templates/screens--OverviewScreen.example.jsx",
        include_str!("../skills/wireframe/templates/screens--OverviewScreen.example.jsx"),
    ),
    (
        "wireframe/templates/screens--screen.example.jsx",
        include_str!("../skills/wireframe/templates/screens--screen.example.jsx"),
    ),
    // --- presentation ---
    (
        "presentation/SKILL.md",
        include_str!("../skills/presentation/SKILL.md"),
    ),
    (
        "presentation/templates/entry-point.jsx",
        include_str!("../skills/presentation/templates/entry-point.jsx"),
    ),
    (
        "presentation/templates/components--deck.jsx",
        include_str!("../skills/presentation/templates/components--deck.jsx"),
    ),
    (
        "presentation/templates/slides--slide.example.jsx",
        include_str!("../skills/presentation/templates/slides--slide.example.jsx"),
    ),
    // --- background-command ---
    (
        "background-command/SKILL.md",
        include_str!("../skills/background-command/SKILL.md"),
    ),
    // --- teamwork-parent ---
    (
        "teamwork-parent/SKILL.md",
        include_str!("../skills/teamwork-parent/SKILL.md"),
    ),
    (
        "teamwork-parent/templates/entry-point.jsx",
        include_str!("../skills/teamwork-parent/templates/entry-point.jsx"),
    ),
    (
        "teamwork-parent/templates/components--TaskNode.jsx",
        include_str!("../skills/teamwork-parent/templates/components--TaskNode.jsx"),
    ),
    (
        "teamwork-parent/templates/components--DependencyEdge.jsx",
        include_str!("../skills/teamwork-parent/templates/components--DependencyEdge.jsx"),
    ),
    (
        "teamwork-parent/templates/data--flow.example.jsx",
        include_str!("../skills/teamwork-parent/templates/data--flow.example.jsx"),
    ),
    // --- teamwork-child ---
    (
        "teamwork-child/SKILL.md",
        include_str!("../skills/teamwork-child/SKILL.md"),
    ),
];
